Awesome books es6 branch
sulaimonaa/awesome-books-es6 pull request #1
Opened 2023-06-14 10:33 UTC by sulaimonaa

#Awesome book with es6
##Uses javascript classes with module
##All other script files are imported to the index.js file
### file workflow structures include index.html, index.css, and index.js

2023-06-14 11:10 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @sulaimonaa 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used ES6 and modules 📌 
✔️ Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 11:10 UTC, codepantha commented on modules/changeState.js
> +}
- [ ] Please use arrow syntax for these functions as stated in the project requirements 👍

2023-06-14 11:10 UTC, codepantha commented on modules/book-store.js
> +            </div>
- [ ] An error occurs when trying to remove a book. Please see the error below and try to fix it 👍 
![image](https://github.com/sulaimonaa/awesome-books-es6/assets/46839548/4302cecf-3f64-49d2-a765-8b323369fd71)

2023-06-15 07:55 UTC, jerryowusu approved these changes
Hi @sulaimonaa 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![chelsea-mason-approve](https://github.com/sulaimonaa/awesome-books-es6/assets/65233860/e787beec-735b-47e5-a002-2e3c885e4b79)


## Highlights
Fixed remove errors :+1: 
Used arrow functions :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 08:05 UTC, closed without merging